# Generated by Django 2.2.2 on 2019-06-15 18:06

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detectionmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=detection.models.get_image_path)),
            ],
        ),
    ]
